### ISSUE TITLE
A list of problems i found

### ISSUE THREAD

**Issue by Lim-it** [Coney-Poney/figura-ponies#2]
+ **The player model is often stuck in a shaking animation, reason unknown**
+ Tall hyppogriff is wrongly labeled as "Tall Pony"
+ The parrot is not visible when it's on player's shoulder(add vanilla_model.PARROTS:setVisible(true) to pony.lua solves the problem)
+ Pinkie Pie model in the community pack is broken

**Comment by winterClover** [comment]
aside from the jitter, the recent commits should address these issues
